version: 1.0.{build}
image: Visual Studio 2019

build_script:
  - npm install
  - npm run build

deploy:
  provider: GitHub
  repository: Elizabess/trello
  branch: gh-pages
  on:
    branch: master
  skip_cleanup: true
  access_token: $GITHUB_TOKEN

artifacts:
  - dist/**
