version: 1.0.{build}
image: Visual Studio 2019

build_script:
  - npm install
  - npm run build

deploy:
  provider: GitHub
  repository: Elizabess/trello
  branch: gh-pages
  on:
    branch: main  # Деплой будет происходить при коммите в master
  skip_cleanup: true
  access_token: $TRELLO_TOKEN  # Убедитесь, что GITHUB_TOKEN настроен правильно

artifacts:
  - dist/**  # Убедитесь, что файлы действительно находятся в этой папке
