version: 1.0.{build}
image: Visual Studio 2019

configuration:
  - Release

build_script:
  - yarn install
  - yarn build

deploy:
  provider: GitHub
  repo: Elizabess/trello
  branch: main
  on_success: always
