version: 1.0.{build}-{commit}
image: Visual Studio 2019

build_script:
  - npm install
  - npm run build

deploy:
    provider: GitHubPages
    branch: main
    folder: dist
    release: true
    auth_token:
      secure: "${{ secrets.GITHUB_TOKEN }}"
    tag: '1.0.${{ github.run_number }}'
   
