version: 1.0.{build}
image: Visual Studio 2019

environment:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

configuration:
  - Release

build_script:
  - echo "Starting build process..."
  - yarn install
  - yarn build

deploy:
  provider: GitHub
  branch: main
  on_success: always
  release: true
  auth_token: ${{ secrets.GITHUB_TOKEN }}
  tag: '1.0.4'
