version: 1.0.{build}
image: Visual Studio 2019

build_script:
  - npm install
  - npm run build

deploy:
  provider: GitHub
  auth_token: $TRELLO_TOKEN  # Убедитесь, что это имя совпадает с тем, что вы настроили
  release: '1.0.6'
  tag: '1.0.6'
  file: 'dist/bundle.js'

artifacts:
  - path: dist/** 
