version: 1.0.{build}
image: Visual Studio 2019

configuration:
  - Release

build_script:
  - yarn install
  - yarn build

deploy:
  provider: GitHub
  branch: main
  on_success: always
  release: true
  auth_token: $GITHUB_TOKEN
  tag: '1.0.4'
