version: 1.0.{build}
image: Visual Studio 2019

environment:
  GITHUB_TOKEN: ${{ secrets.TRELLO_TOKEN }}

configuration:
  - Release

build_script:
  - echo "Starting build process..."
  - yarn install
  - yarn build

deploy:
  provider: GitHub
  branch: main
  auth_token: ${{ secrets.TRELLO_TOKEN }} 
  tag: '1.0.${{ github.run_number }}'
