name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: npm install && npm run build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "1.0.${{ github.run_number }}"
          release_name: "Release 1.0.${{ github.run_number }}"
          body: "Описание релиза"
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.TRELLO_TOKEN }} # Используйте ваш токен здесь
